package com.milba_Ittech.jobreport.domain.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

// ─── AcUnit ──────────────────────────────────────────────────────────────────
// Table: ac_units
// No longer has ticket_id — linked to tickets via ticket_ac_units junction table
// ac_code is auto-generated by DB: AC-YYYY-0000001

@Serializable
data class AcUnit(
    val id:               String,
    @SerialName("ac_code")
    val acCode:           String,
    @SerialName("location_id")
    val locationId:       String,
    @SerialName("building_unit_id")
    val buildingUnitId:   String,
    @SerialName("brand_id")
    val brandId:          String,
    val type:             String,                   // Split | Cassette | Standing | Ducted | Window | Portable
    @SerialName("capacity_pk")
    val capacityPk:       String,                   // 0.5 PK | 0.75 PK | 1 PK | 1.5 PK | 2 PK | 2.5 PK | 3 PK
    @SerialName("unit_label")
    val unitLabel:        String  = "1",
    @SerialName("access_notes")
    val accessNotes:      String? = null,
    @SerialName("last_cleaned_at")
    val lastCleanedAt:    String? = null,
    @SerialName("is_active")
    val isActive:         Boolean = true,
    val notes:            String? = null
)

// ─── AcUnit with joined display name (for technician screens) ────────────────
// Used when fetching ticket_ac_units with nested ac_units + building_units

@Serializable
data class AcUnitWithDisplay(
    val id:               String,
    @SerialName("ac_code")
    val acCode:           String,
    val type:             String,
    @SerialName("capacity_pk")
    val capacityPk:       String,
    @SerialName("unit_label")
    val unitLabel:        String  = "1",
    @SerialName("access_notes")
    val accessNotes:      String? = null,
    // Joined from building_units
    @SerialName("building_units")
    val buildingUnit:     BuildingUnitDisplay? = null
) {
    val displayName: String get() = buildingUnit?.displayName ?: unitLabel
    val label: String get() = "$acCode · $type · $capacityPk"
}

// ─── TicketAcUnit ─────────────────────────────────────────────────────────────
// Junction row from ticket_ac_units with nested ac_units data
// Used in: TicketRepository.getTicketAcUnits(ticketId)

@Serializable
data class TicketAcUnit(
    @SerialName("order_number")
    val orderNumber: Int,
    @SerialName("ac_units")
    val AcUnit:      AcUnitWithDisplay
)

// ─── BuildingUnit ─────────────────────────────────────────────────────────────
// Table: building_units
// display_name is auto-generated by DB trigger: "{zone} → {floor} → {room}"

@Serializable
data class BuildingUnit(
    val id:           String,
    @SerialName("location_id")
    val locationId:   String,
    val zone:         String? = null,
    val floor:        String? = null,
    val room:         String,
    @SerialName("display_name")
    val displayName:  String,
    val notes:        String? = null
)

// Minimal nested model for joins
@Serializable
data class BuildingUnitDisplay(
    @SerialName("display_name")
    val displayName: String
)